# .github/workflows/publish.yml

name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Write access is needed for pushing changelog changes and tags
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Install dependencies (ensure you have the necessary configuration and release-please in package.json)
      - name: Install dependencies
        run: npm install

      # Use the release-please action to create a changelog and version tag
      - name: Generate changelog and version
        uses: googleapis/release-please-action@v3
        with:
          release-type: node
          package-name: your-package-name  # Replace with your package name if applicable
          versioning-strategy: increase  # Adjust strategy if needed (e.g., "auto", "increase", etc.)

      # Run your publishing step (e.g., for npm or your package)
      - name: Publish
        run: npx jsr publish

      # Push changes (including changelog and tags) back to GitHub
      - name: Push changes and tags back to GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push --follow-tags
