jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple

  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish